### ISSUE TITLE
azureml dependencies needed in environment

### ISSUE THREAD

**Issue by samuel100** [Azure/AML-Kubernetes#90] opened 2021-05-07 15:15 UTC
A user needs to include azureml dependencies in their environment (see bold below). They should not need to do this - it is different to the side-car method used on AmlCompute.

name: pytorch-env
channels:
    - defaults
    - pytorch
dependencies:
    - python=3.7.0
    - pytorch
    - torchvision
    - pip:
      - mlflow
      **- azureml-mlflow
      - azureml-core
      - azureml-dataprep[pandas,fuse]**

**Comment by Bozhong68** [comment] 2021-12-01 19:56
closing the issue - the issue is addressed with common runtime integration

**Closed by Bozhong68** 2021-12-01 19:56 UTC
