### ISSUE TITLE
Cannot connect Azure Arc Kubernetes cluster to Azure ML Studio

### ISSUE THREAD

**Issue by idanilescu** [Azure/AML-Kubernetes#141] opened 2021-11-12 14:00 UTC
Hello,

I have been trying to connect a kubernetes cluster deployed on a physical server to Azure ML Studio. The setup runs just fine but the install state on azure portal shows failed.
The command I used to install the ML extension is:

```bash
az k8s-extension create --name arcml-extension --extension-type Microsoft.AzureML.Kubernetes --cluster-name mltest --resource-group --config enableInference=True allowInsecureConnections=True --cluster-type connectedClusters --scope cluster
```

This is the error message:

```json
"statuses": [
  {
    "code": "InstallationFailed",
    "displayStatus": null,
    "level": null,
    "message": "Error: {failed to install chart from path [] for release [arcml-extension]: err [unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version admissionregistration.k8s.io/v1beta1"]} occurred while doing the operation : {Installing the extension} on the config",
    "time": null
  }
]
```

I have checked the network related pre-reqs and everything looks fine. I have also tried installing the extension using the training config only and it works just fine. The Kubernetes version I am using is 1.22.2. Can someone guide me in troubleshooting this issue ? Thanks

**Comment by richeney** [comment] 2021-11-12 15:55
Note that the above issue is impacting a current Azure customer opportunity.

Is it possible to prioritise accordingly?

**Comment by Zhong-J** [comment] 2021-11-15 12:44
+ @mjaow  Do you have any thoughts? 
@idanilescu , feel free to find me via jinzhong@microsoft.com . I can set up a debugging session if needed.

**Comment by mjaow** [comment] 2021-11-15 13:27
Hi, k8s 1.22 has deprecated api version for admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

You can try 1.18,1.19 or 1.20, here is list for what we support: https://github.com/Azure/AML-Kubernetes#supported-kubernetes-distributions-and-versions

**Comment by Bozhong68** [comment] 2021-12-01 19:39
tracking the issue with an internal work item, closing the issue.

**Closed by Bozhong68** 2021-12-01 19:39 UTC

**Comment by joaocc** [comment] 2021-12-11 12:41
Hi.
Could you share any plans on when support for 1.22 would be available?
None of the versions mentioned above is up to date, as per MSFT support information from https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions :
* 1.19 is already deprecated, and extended till end of 21M01 as grace period
* 1.20 has already reached EOL (due to 1.23 having launched a couple of days ago)
Thanks

**Comment by Zhong-J** [comment] 2021-12-13 07:52
Hi Joao,

We have verified K8s 1.21.x, which works well on ML extension. We are working on the verification and support on 1.22.x, which we target end of Dec. to officially support. We will update the document once we officially support it 😊

Thanks,
Doris

**Comment by joaocc** [comment] 2021-12-13 08:58
Thanks. 
Since my comment I confirmed that things seem to work well with 1.21. 
Looking forward to 1.22 support.
Cheers
